### ISSUE TITLE
How to remove the component after I mount it (more details in desc)

### ISSUE THREAD

**Issue by harshsbais** [Steve-Junior/tawkto-react#10]
I am mounting the component in my home page using this package but want it removed when I open dashboard. Can you please help how can I do so.

**Comment by stephen-ifmacinema** [comment]
Just make sure you are mounting it only in the home page component, one that component is unmounted, tawk will be unmounted with it

**Comment by harshsbais** [comment]
I'm mounting like this. Can you please tell me what to write in return 
```
useEffect(() => {
    tawkTo(tawkToPropertyId, tawkToKey)
    return () => {
    //what to write here
    };
}, [])
```

**Comment by ghost** [comment]
@harshsbais, this package has been updated.

Now you can

`let tawk = null;
useEffect(() => {
    tawk = new TawkTo(propertyId, tawkId)
    return () => {
    //what to write here
    };
}, [tawk])`

Finally, add `tawk` to context or prop drill it to a child component. Hope it helps!
