### ISSUE TITLE
Error code : GET {link} net::ERR_ABORTED 400

### ISSUE THREAD

**Issue by codenm007** [Steve-Junior/tawkto-react#11]
Getting this above error code when implementing inside react useffect ,  I have checked the property id and key and they are correct , please help me asap !

**Comment by Q8root** [comment]
Getting the same error

**Comment by CarlosFandango** [comment]
+1

**Comment by frabanca** [comment]
@codenm007 Have you tried to use 'default' as key?

I mean from this:
```typescript
tawkTo(config.tawk.propertyId, config.tawk.key);
```

To this:
```typescript
tawkTo(config.tawk.propertyId, 'default');
```

It's not a real solution since it only works if you want to use the default key/account.

**Comment by rozenteno** [comment]
+1

**Comment by jasirtp** [comment]
> Getting this above error code when implementing inside react useffect , I have checked the property id and key and they are correct , please help me asap !

same have u solved?

**Comment by codenm007** [comment]
Use it as an IIFE expression, you don't need to use a library to integrate tawk-to with react!
Code below for ref : 
  ```
              (function(){
                    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
                    s1.async=true;
                    s1.src='https://embed.tawk.to/{your tawkto key}';
                    s1.charset='UTF-8';
                    s1.setAttribute('crossorigin','*');
                    s0.parentNode.insertBefore(s1,s0);
                    })()
```

**Comment by jasirtp** [comment]
Solved any way
Thank you for your valuable time


Thanks & Regards
>
> Jasir
>
>
>
