### ISSUE TITLE
help me  in react tsx

### ISSUE THREAD

**Issue by KoddyDev** [Steve-Junior/tawkto-react#17]
Could not find a declaration file for module 'tawkto-react'. '/var/www/pterodactyl/node_modules/tawkto-react/src/index.js' implicitly has an 'any' type.

**Comment by andrespinog** [comment]
Declare it in your global.d.ts file:

`declare module 'tawkto-react'`

**Comment by ghost** [comment]
Since there is no further concern, I will close this issue. Thank you
