### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Milankorangi** [Steve-Junior/tawkto-react#18]
its not working in react

**Comment by stephen-ifmacinema** [comment]
What error are you getting?
What exactly is not working?
What have you tried?

**Comment by Milankorangi** [comment]
@stephen-ifmacinema i used this code in app.js but it did not load anything. i used key from twak dashboard.

import tawkTo from "tawkto-react";

const tawkToPropertyId = 'get_property_id_from_tawkto_dashboard'
const tawkToKey = 'get_key_from_tawkto_dashboard'

useEffect(() => {
    tawkTo(tawkToPropertyId, tawkToKey)
}, [])

**Comment by ghost** [comment]
Hello @Milankorangi

I have updated the package and elaborated more in the README on how to use the package properly. Hope it helps!

**Comment by Steve-Junior** [comment]
Hello @Milankorangi

I have updated the package and elaborated more in the README on how to use the package properly. Hope it helps!
