### ISSUE TITLE
How can I use JavaScript API using this package?

### ISSUE THREAD

**Issue by cheshirrrcat** [Steve-Junior/tawkto-react#19]
Can you help me how can I use these API commands?
https://developer.tawk.to/jsapi/

For example, I need to showWidget() by click on the button.

**Comment by ghost** [comment]
Sure @cheshirrrcat. The next package will come with those wrappers

**Comment by ghost** [comment]
@cheshirrrcat as promised. Check out the latest version 3.0.0 for more functionalities and customisation.

Hope it helps!
