### ISSUE TITLE
FEATURE Request: Need unsubscribe method

### ISSUE THREAD

**Issue by shahriarpshuvo** [Steve-Junior/tawkto-react#20]
The behavior I'm expecting is, if the user exits from a page the chat widget will not show up.
Need a function to unsubscribe on page exit on useEffect.
I'm interested to work on that.

**Comment by ghost** [comment]
Hey @Mr-spShuvo, You asked for this feature. Now it's available. 

Update to the latest version to get it. ✌🏻

**Comment by barrymichaeldoyle** [comment]
@Steve-Junior how to do we call that function? I don't see it in the src.
