### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ChanukaSandeepa** [Steve-Junior/tawkto-react#21]
Nothing happen. It doesn't give even an error.

**Comment by ghost** [comment]
Hello @ChanukaSandeepa, I am not sure why you facing this issue.

Kindly update the current version, follow the usage guideline, and let us know if the issue persists.

**Comment by Steve-Junior** [comment]
Hello @ChanukaSandeepa, I am not sure why you facing this issue.

Kindly update the current version, follow the usage guideline, and let us know if the issue persists.
