### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by oneHumanInDev** [Steve-Junior/tawkto-react#23]
There is not enough information of how to implement this chat, also. following your functional component, it still not working useEffect shows as empty in the devtools.

**Comment by andrem0** [comment]
@oneHumanInDev 

```
import { useEffect } from "react";

function TawkTo() {
  const tawkTo = require("tawkto-react");

  const tawkToPropertyId = "YOUR-ID";

  useEffect(() => {
    tawkTo(tawkToPropertyId);
  }, []);

  return null;
}

export default TawkTo;
```

**Comment by muftisamiullah** [comment]
i get a 404 error on the embed link, most probably tawk.to has changed the embed link

**Comment by daniego** [comment]
@muftisamiullah I was experiencing the same 404 as you once I realised that I was using the wrong `tawkToKey `.
I my case I was using the `Javascript API KEY` instead  of the correct one available from the "Chat widget" panel

**Comment by muftisamiullah** [comment]
I couldn't find the issue i was using the correct key only, i ended up uninstalling this package and doing everything on my own and it was so simple

**Comment by ghost** [comment]
The new package update and the README should be clear enough to use. 
I also indicated how to get your productID and tawkID from the panel in an image. With the correct credentials, this 404 error should not occur.
