### ISSUE TITLE
./node_modules/tawkto-react/src/index.js Module parse failed: Unexpected character '#' (15:22)       

### ISSUE THREAD

**Issue by yongting1992** [Steve-Junior/tawkto-react#29]
You may need an appropriate loader to handle this file type.
| class TawkTo {
|   constructor(propertyId, widgetId, zIndex = null) {      
|     this._Tawk = this.#init(propertyId, widgetId, zIndex);
|   }

updated to version 3.0.0 and getting this error

**Comment by ghost** [comment]
First, another issue was already for this same bug. I have rolled out an update to fix it v3.0.1
