### ISSUE TITLE
Does this work on local?

### ISSUE THREAD

**Issue by zehawki** [Steve-Junior/tawkto-react#30]
Did you get this working on your local setup? 

I can see a number of scripts being loaded.

![image](https://user-images.githubusercontent.com/8095144/149677144-5a6035d4-606c-4b91-bccb-10f2ba6095ab.png)

and I can see that an iframe has been inserted on the bottom right, exactly where the widget should first show up. 

![image](https://user-images.githubusercontent.com/8095144/149677177-7b7b7c83-5b2e-4a13-b5ba-d3a1e659d596.png)

But nothing actually does show up.

PS: This is probably nothing to do with the wrapper, but more to do with Tawkto itself.

**Comment by ghost** [comment]
Shweuu! I double-checked and see no reason why you should be having this issue. I advise you to test on other browsers, especially Chrome. It will be difficult to assist you without proper context.

**Comment by zehawki** [comment]
This above is from chrome.
