### ISSUE TITLE
Style the TawkTo Iframe

### ISSUE THREAD

**Issue by Mihai-github** [Steve-Junior/tawkto-react#31]
Hi,
   Is there a way to customize the style of the TawkTo because is in an iframe from what I can see and w/o any prop or something it's kinda not doable...

Thanks :)

**Comment by ghost** [comment]
Hello @Mihai-github 

var tawkto = new TawkTo(propertyId, widgetId, zIndex)

Currently, the only styling component supported is zIndex can be an int or string value.

**Comment by Mihai-github** [comment]
Ok, I see. Anyway nice job with this library. I hope more people will start using it 🙏 so we are going to see more and more features added 😀
