### ISSUE TITLE
Unable to add visitor info

### ISSUE THREAD

**Issue by TheUltimateCookie** [Steve-Junior/tawkto-react#32]
I'm unable to add user info after initializing tawk. Any advice?

**Comment by gideongandrapu** [comment]
go through this https://developer.tawk.to/jsapi/
And I faced the same issue.. but you need to wait till you get the user details in your application.
Or mount Tawk after completing page load.

**Comment by TheUltimateCookie** [comment]
I meant via, the plugin. I couldn't find that so I accomplished this with basic js stuff

**Comment by harnie2275** [comment]
Why is @Steve-Junior closing this case, we are still facing this issue even when user detail is available
