### ISSUE TITLE
Chat widget choice

### ISSUE THREAD

**Issue by melvinlemoine** [Steve-Junior/tawkto-react#4]
Hello ! Thank you for your work.
Do you think it's possible to add the possibility to select the chat widget ? Because I have multiples chat widget for different pages & situation, like error pages that I want the error chat widget. Do you see ?

Regards

**Comment by stephen-ifmacinema** [comment]
Just to be clear, this code works for [tawk.to](https://tawk.to) apps only. 

Invoke tawkTo() in each page instead of the root component and pass in the different (tawkto) property Ids based on the page the user is in.

Hope it helps!

**Comment by melvinlemoine** [comment]
Hello there.
Thank you for your informations ! That's perfect.
