### ISSUE TITLE
/default not working

### ISSUE THREAD

**Issue by ghost** [Steve-Junior/tawkto-react#8]
When I add the PropertyID I can't see the chat box.
I found the issue.

Now the URL is: _https://embed.tawk.to/PROPERTY_ID/default_
My chat has not "default" as parameter but unique key. 

So it should be: _https://embed.tawk.to/PROPERTY_ID/KEY_
When I open the URL with the right /KEY (and not /default) I got a response back and see JS code.

Maybe you can have a look into it?

**Comment by drixie** [comment]
Same issue here. @Steve-Junior I submitted a PR to fix it

**Comment by ghost** [comment]
It is resolved
